function Verify_Public_Repo_Smoke()
%VERIFY_PUBLIC_REPO_SMOKE  Lightweight runtime smoke tests for public repo.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repoRoot, 'src'));

smokeRoot = fullfile(repoRoot, 'outputs', 'Smoke_Test');
if ~exist(smokeRoot, 'dir')
    mkdir(smokeRoot);
end

fprintf('=== Public Repo Smoke Test ===\n');
fprintf('Output root: %s\n\n', smokeRoot);

surfaceCfg = struct(...
    'material', 'W', ...
    'Pavg', 5, ...
    'spotRadius', 100e-6, ...
    'f_rep', 1e6, ...
    'tau_FWHM', 500e-15, ...
    'absorbance', 0.55, ...
    'simDuration', 5 / 1e6, ...
    'makePlots', false, ...
    'saveFigures', false, ...
    'outputDir', fullfile(smokeRoot, 'Surface_Point'));
surfaceResults = Surface_Point_Solver(surfaceCfg);
verifyCommonContract(surfaceResults, 'surface_point');
assert(isfield(surfaceResults, 'peakTe_C'));
assert(exist(surfaceResults.outputFile, 'file') == 2);

depthCfg = struct(...
    'material', 'W', ...
    'Pavg', 20, ...
    'spotRadius', 100e-6, ...
    'f_rep', 5e6, ...
    'tau_FWHM', 500e-15, ...
    'absorbance', 0.55, ...
    'simDuration', 5 / 5e6, ...
    'makePlots', false, ...
    'saveFigures', false, ...
    'enableRadialProfile', false, ...
    'outputDir', fullfile(smokeRoot, 'Depth_Profile'));
depthResults = Depth_Profile_Solver(depthCfg);
verifyCommonContract(depthResults, 'depth_profile');
assert(isfield(depthResults, 'nPulses'));
assert(exist(depthResults.outputFile, 'file') == 2);

radialCfg = struct(...
    'material', 'W', ...
    'Pavg', 20, ...
    'spotRadius', 100e-6, ...
    'f_rep', 5e6, ...
    'tau_FWHM', 500e-15, ...
    'absorbance', 0.55, ...
    'simDuration', 5 / 5e6, ...
    'Nr', 30, ...
    'rMax_factor', 3, ...
    'radialSolveMode', 'scale', ...
    'makePlots', false, ...
    'saveFigures', false, ...
    'outputDir', fullfile(smokeRoot, 'Radial_Profile'));
radialResults = Radial_Profile_Solver(radialCfg);
verifyCommonContract(radialResults, 'radial_profile');
assert(isfield(radialResults, 'finalRadialProfile_C'));
assert(exist(radialResults.outputFile, 'file') == 2);

singlePulseCfg = struct(...
    'material', 'W', ...
    'Pavg', 5, ...
    'spotRadius', 100e-6, ...
    'f_rep', 1e6, ...
    'tau_FWHM', 500e-15, ...
    'absorbance', 0.55, ...
    'simDuration', 1 / 1e6, ...
    'makePlots', false, ...
    'saveFigures', false, ...
    'outputDir', fullfile(smokeRoot, 'Single_Pulse'));
singlePulseResults = Single_Pulse_Visualizer(singlePulseCfg);
verifyCommonContract(singlePulseResults, 'single_pulse');
assert(isfield(singlePulseResults, 'peakTe_C'));
assert(exist(singlePulseResults.outputFile, 'file') == 2);

inversionCfg = struct(...
    'material', 'W', ...
    'Pavg', 20, ...
    'spotRadius', 100e-6, ...
    'f_rep', 5e6, ...
    'tau_FWHM', 500e-15, ...
    'absorbance', 0.55, ...
    'simDuration', 5 / 5e6, ...
    'makePlots', false, ...
    'saveFigures', false, ...
    'enableRadialProfile', false, ...
    'outputDir', fullfile(smokeRoot, 'Inversion'));
inversionResults = Inversion_Quantifier(inversionCfg);
verifyCommonContract(inversionResults, 'inversion_quantifier');
assert(isfield(inversionResults, 'meanInv_K'));
assert(exist(inversionResults.outputFile, 'file') == 2);

scanParams = struct(...
    'material', 'W', ...
    'Pavg', 10, ...
    'spotRadius', 100e-6, ...
    'f_rep', 1e5, ...
    'tau_FWHM', 500e-15, ...
    'pulseProfile', 'gaussian', ...
    'v_scan', 1.0, ...
    'scanLength', 5 / 1e5, ...
    'absorbance', 0.55, ...
    'Leff', 100e-9, ...
    'T0_C', 25, ...
    'Nx', 20, ...
    'Ny', 12, ...
    'xPad', 2, ...
    'yExtent', 3, ...
    'depthProfile', 'exponential', ...
    'dzTarget', 500e-9, ...
    'Ndiff', 10, ...
    'NadiPerGap', 2);
scanResults = Scanning_Beam_Solver(scanParams, fullfile(smokeRoot, 'Scanning_Beam'), false);
verifyCommonContract(scanResults, 'scanning_beam');
assert(isfield(scanResults, 'peakT_history'));
assert(exist(scanResults.outputFile, 'file') == 2);

fprintf('\nAll smoke tests passed.\n');
end

function verifyCommonContract(results, expectedSolverId)
requiredFields = {
    'solver', ...
    'solverId', ...
    'contractVersion', ...
    'material', ...
    'outputFile', ...
    'outputDir', ...
    'inputConfig'};

for i = 1:numel(requiredFields)
    assert(isfield(results, requiredFields{i}), 'Missing required field: %s', requiredFields{i});
end

assert(strcmp(results.contractVersion, 'v1'), 'Unexpected contractVersion');
assert(strcmp(results.solverId, expectedSolverId), 'Unexpected solverId');
assert(ischar(results.outputFile) || isstring(results.outputFile), 'outputFile must be text');
assert(ischar(results.outputDir) || isstring(results.outputDir), 'outputDir must be text');
end